name: Build

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cobridge/ros-foxy:24.09.06

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: src/coListener

      - name: build
        run: |          
          VERSION=${GITHUB_REF#refs/tags/}
          echo "current version: $VERSION"
          echo "$VERSION" > version
          cat version
          /ros_entrypoint.sh colcon build --packages-select coListener

      - name: zip-artifact
        run: zip -r install.zip install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coListener
          path: install.zip

